name: Node.js CI

on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm i
      - run: npm run build --if-present
      - run: npm test